In [1]:
import numpy as np

### Creating NumPy array

In [2]:
a = np.array([1,2,3,4]) # using a list
print(a)

[1 2 3 4]


In [5]:
b = np.array((1,2,3,4)) # using a tuple
print(b)

[1 2 3 4]


In [6]:
c = np.array([[1,2,3,4],[10,20,30,40]]) # 2-D numpy array
print(c)

[[ 1  2  3  4]
 [10 20 30 40]]


### dimensions in np array

In [24]:
a.ndim

1

In [25]:
c.ndim

2

In [32]:
## 3-D NumPy Array

t = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(t)
print("\nNumber of dimensions in the above array: ",t.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]

Number of dimensions in the above array:  3


### np array : dtype vs type
dtype - this will return type of data with size that is contained in the np array \
type - this will return 'np array'

In [9]:
a.dtype, b.dtype, c.dtype   

(dtype('int32'), dtype('int32'), dtype('int32'))

In [10]:
s = np.array(['apple','lenovo','hp'])
s.dtype  

dtype('<U6')

In [16]:
p = np.array(['a','c','d'])
p.dtype

(dtype('<U1'), numpy.ndarray)

In [35]:
t.dtype, type(t)

(dtype('int32'), numpy.ndarray)

In [33]:
for arr in [a,b,c,s,p,t]:
    print(type(arr))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### Accessing np array data - slicing
#### arr[row start : end : step size, column start : end : step size]
#### arr[row start:end, column start: end] ----- here the step size would be 1 by default

In [17]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr[0:2, 0:3] ## first two rows and first 3 columns

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr[:2, :3]  ## same thing as above, we can skip writing 0 for first index.

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr[::2,1:3]  ## all row indexes with step size 2 i.e., row 0 and 2. Columns from 1 to 2

array([[2, 3],
       [8, 9]])